name: Build and Publish

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Yarn Install
              run: yarn
            - name: Run Build and Publish Script
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  year=$(date +%Y)
                  versionMinor=$(date +%m.%d%H%M)
                  let versionMajor=$year-2020
                  version=$versionMajor.$versionMinor

                  yarn build:custom:publish -v $version
            - name: Log into GitHub CLI
              run: |
                  echo ${{secrets.GH_CLI_AUTH_TOKEN}} > gh.txt
                  gh auth login --with-token < gh.txt
            - name: Create GitHub Release
              run: gh release create ${{ steps.time.outputs.time }} ./dist
