name: Build and Publish

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Yarn Install
              run: yarn
            - name: Get Year
              id: year
              uses: nanzm/get-time-action@v1.1
              with:
                  timeZone: 8
                  format: "YYYY"
            - name: Get Time
              id: time
              uses: nanzm/get-time-action@v1.1
              with:
                  timeZone: 8
                  format: "M.DDHHmm"
            - name: Run Build and Publish Script
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  YEAR: ${{ steps.year.outputs.time }}
              run: |
                  echo ::set-env name=VERSION::"$(($YEAR-2020)).${{ steps.time.outputs.time }}"
                  yarn build:custom:publish -v $VERSION

            - name: Log into GitHub CLI
              run: |
                  echo ${{secrets.GH_CLI_AUTH_TOKEN}} > gh.txt
                  gh auth login --with-token < gh.txt
            - name: Create GitHub Release
              run: gh release create ${{ steps.time.outputs.time }} ./dist
